AWSTemplateFormatVersion: 2010-09-09

### Paramters ####
Parameters:
  ImageId:
    Type: String
    Default: "ami-0aeeebd8d2ab47354"
  
  InstanceType:
    Type: String
    Default: t2.nano
    AllowedValues:
      - t2.nano
      - t2.small
      - t2.micro
      - t2.medium

  SubnetId:
    Type: String

  KeyName:
    Type: String

  EnvTag:
    Type: String

  TeamTag:
    Type: String


### Resources ####
Resources:
  TestEC2instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - !ImportValue TestSecurityGroup
      Tags:
        - Key: Env
          Value: !Ref EnvTag
        - Key: TeamTag
          Value: !Ref TeamTag
      


### Outputs ###
Outputs:
  TestEC2instanceId:
    Description: "EC2 Id"
    Value: !Ref TestEC2instance
  
  TestEC2PublicIP:
    Description: "EC2 public ip"
    Value: !GetAtt TestEC2instance.PublicIp